### ISSUE TITLE
Using Client Server

### ISSUE THREAD

**Issue by PedroPCardoso** [sonata-nfv/son-emu#251]
Hello, I'm trying to add a docker server and a client, the problem is that I need to know the ip of the server. I am trying to get the ip address of the server, but I can not find the ip address of the server. do ?

**Comment by mpeuster** [comment]
Hi, 
assuming you server container is called `d1` and you client is called `d2`, you can do:

```
containernet> d1 ifconfig
```

to see the IPs of the server.

However, can you link/paste the commands you are using to start the containers? The used topology etc.? 

And, also important, the used containers need to follow [these requirements](https://github.com/sonata-nfv/son-emu/wiki/Container-Requirements) in order to work with son-emu. This especially means that your server software in the container needs to be started in a "non-blocking" way so that son-emu can interact with the container's shell.

**Comment by PedroPCardoso** [comment]
no caso, eu tenho uma imagem docker, preciso usar o EXPOSE  20001 na imagem ?

Meu arquivo de server.py
``# Multithreaded Python server : TCP Server Socket Program Stub
TCP_IP = '0.0.0.0' 
TCP_PORT = 2004 
BUFFER_SIZE = 20  # Usually 1024, but we need quick response 
 
tcpServer = socket.socket(socket.AF_INET, socket.SOCK_STREAM) 
tcpServer.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1) 
tcpServer.bind((TCP_IP, TCP_PORT)) 
threads = [] 
 
while True: 
    tcpServer.listen(4) 
    print "Multithreaded Python server : Waiting for connections from TCP clients..." 
    (conn, (ip,port)) = tcpServer.accept() 
    newthread = ClientThread(ip,port) 
    newthread.start() 
    threads.append(newthread)

**Comment by PedroPCardoso** [comment]
in case, I have a docker image, do I need to use EXPOSE 20001 in the image?

My server.py file

# Multithreaded Python server : TCP Server Socket Program Stub
TCP_IP = '0.0.0.0' 
TCP_PORT = 2004 
BUFFER_SIZE = 20  # Usually 1024, but we need quick response 
 
tcpServer = socket.socket(socket.AF_INET, socket.SOCK_STREAM) 
tcpServer.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1) 
tcpServer.bind((TCP_IP, TCP_PORT)) 
threads = [] 
 
while True: 
    tcpServer.listen(4) 
    print "Multithreaded Python server : Waiting for connections from TCP clients..." 
    (conn, (ip,port)) = tcpServer.accept() 
    newthread = ClientThread(ip,port) 
    newthread.start() 
    threads.append(newthread)

**Comment by mpeuster** [comment]
No, `EXPOSE` is not required for the interfaces of the emulated network, only for the Docker management interfaces. 

I assume this code runs inside a container that is started in the emulation? How do you start this code, because it it blocking (`while True`)?
